batchsize: 8
iteration: 1000
iteration_decay_start: 0
seed: 0
display_interval: 1
snapshot_interval: 1
evaluation_interval: 1

patch:
  patchside: 92
  interval: 0

unet:
  fn: model_nopad.py

updater:
  fn: updater.py

adam:
  alpha: 0.001
  beta1: 0.9
  beta2: 0.999
