batchsize: 32
iteration: 15000
iteration_decay_start: 0
seed: 0
display_interval: 100
snapshot_interval: 300
evaluation_interval: 300

patch:
  patchside: 44
  interval: 0

unet:
  fn: model_nopad.py

updater:
  fn: updater.py

adam:
  alpha: 0.001
  beta1: 0.9
  beta2: 0.999
